version: "3"
services:

  # app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   depends_on:
  #     - postgres
  #   environment:
  #     - DB_HOST=postgres
  #     - DB_PASSWORD=abc123
  #   volumes:
  #     - ./:/code
  #   ports:
  #     - "5005:80"

  mysql:
    image: mysql:5
    environment:
      MYSQL_ROOT_PASSWORD: abc123
    ports:
      - "3306:3306"

  postgres:
    image: postgres:9.6-alpine
    environment:
      - POSTGRES_USER=allocation
      - POSTGRES_PASSWORD=abc123
    ports:
      - "5432:5432"